services:
  postgres18:
    image: postgres:18
    shm_size: 128mb
    ports:
      - "5444:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres18:/var/lib/postgresql/18/docker # new path from 18th release